name: verify commit signatures

on:
  pull_request:   # github.event.pull_request.head.sha
    branches: [main]

permissions:
  contents: read

env:
  IDENTITY: noizy.sthlm@gmail.com
  ISSUER: https://accounts.google.com
  IDENTITY2: ivboq001@gmail.com
  ISSUER2: https://accounts.google.com

jobs:
  verify:
    runs-on: ubuntu-latest  # https://github.com/actions/runner-images
    steps:
    - uses: actions/checkout@v7 # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: install gitsign
      run: |
        curl -sSfLO https://github.com/sigstore/gitsign/releases/download/v0.17.1/gitsign_0.17.1_linux_amd64.deb
        sudo apt-get install -y ./gitsign_0.17.1_linux_amd64.deb
    
    - name: verify each commit in the pull request
      env:
        BASE_REF: ${{ github.base_ref }}
      run: |
        commits="$(git rev-list origin/${BASE_REF}..HEAD)"
        for commit in $commits; do
          echo "Verifying commit $commit"
          gitsign verify --certificate-identity $IDENTITY --certificate-oidc-issuer $ISSUER $commit \
            || gitsign verify --certificate-identity $IDENTITY2 --certificate-oidc-issuer $ISSUER2 $commit
        done